### ISSUE TITLE
How to download It?

### ISSUE THREAD

**Issue by ykla** [JohnWordsworth/plist-pad#4]
plist-pad-x64-installer-0-1-0.exe
But where is It?

**Comment by MobileManiC** [comment]
Official page is here:
https://www.johnwordsworth.com/projects/plist-pad/

But links on this page are malformed/broken, unfortunately...

Found it here after some digging:
https://www.johnwordsworth.com/downloads/plistpad/plist-pad-x64-installer-0-1-0.exe
https://www.johnwordsworth.com/downloads/plistpad/plist-pad-x64-0-1-0.zip

Still, the app is too early alpha version, it just simply does not work in most cases, so not too much reason to bother with this app at the moment.. Maybe Apple pList format is developing as well, so this app would need constant development as well...
